name: Cleanup and Push Icons & JSON to Root

on:
  push:
    branches:
      - main
    paths:
      - 'icons/**'  
      - 'json/**'   
  workflow_dispatch:

jobs:
  clean_and_move_images:
    if: ${{ github.event.head_commit.modified && contains(github.event.head_commit.modified, 'icons') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Switch to "Images" branch
      run: |
        git fetch origin Images
        git checkout Images
        git reset --hard origin/main  # Hard reset to main

    - name: Delete everything except /icons/
      run: |
        find . -mindepth 1 -maxdepth 1 ! -name "icons" ! -name ".git" -exec rm -rf {} +

    - name: Move icons to root
      run: |
        mv icons/* .
        rmdir icons

    - name: Commit changes to Images branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Moved icons to root and cleaned Images branch" || echo "No changes to commit"

    - name: Push changes to Images branch
      run: |
        git push origin Images

  clean_and_move_json:
    if: ${{ github.event.head_commit.modified && contains(github.event.head_commit.modified, 'json') }}  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Switch to "JSON" branch
      run: |
        git fetch origin JSON
        git checkout JSON
        git reset --hard origin/main  # Hard reset to main

    - name: Delete everything except /json/
      run: |
        find . -mindepth 1 -maxdepth 1 ! -name "json" ! -name ".git" -exec rm -rf {} +

    - name: Move json to root
      run: |
        mv json/* .
        rmdir json

    - name: Commit changes to JSON branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Moved json to root and cleaned JSON branch" || echo "No changes to commit"

    - name: Push changes to JSON branch
      run: |
        git push origin JSON
